### ISSUE TITLE
Иногда падает страница с контестом

### ISSUE THREAD

**Issue by MikeMirzayanov** [Codeforces/polygon-issue-tracking#199]
FATAL [2017-08-11 17:59:05,502] RequestDispatcher: Can't process http://polygon.codeforces.com/contest. (RequestDispatcher.java:114, http-bio-8081-exec-13)
java.lang.NullPointerException
        at com.codeforces.polygon.dao.impl.ContestPropertyDaoImpl.findLanguages(ContestPropertyDaoImpl.java:112)
        at com.codeforces.polygon.web.misc.ApplicationModule.lambda$addDebugBinder$3(ApplicationModule.java:228)
        at com.codeforces.polygon.web.page.ContestPage.initializeAction(ContestPage.java:159)
        at com.codeforces.polygon.web.misc.ApplicationModule.lambda$addDebugBinder$3(ApplicationModule.java:228)
        at org.nocturne.main.Page.parseTemplate(Page.java:143)
        at com.codeforces.polygon.web.misc.ApplicationModule.lambda$addDebugBinder$3(ApplicationModule.java:228)
        at org.nocturne.main.RequestDispatcher.runProductionService(RequestDispatcher.java:105)
        at org.nocturne.main.RequestDispatcher.doFilter(RequestDispatcher.java:294)
        at org.nocturne.main.DispatchFilter.doFilter(DispatchFilter.java:89)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at com.codeforces.csrf.CsrfPreventionFilter.internalDoFilter(CsrfPreventionFilter.java:276)
        at com.codeforces.csrf.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:236)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at com.codeforces.polygon.web.misc.InterceptFilter.doFilter(InterceptFilter.java:26)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at de.javakaffee.web.msm.RequestTrackingContextValve.invoke(RequestTrackingContextValve.java:99)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:156)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)

**Comment by FrolovAlex** [comment]
Fixed, will be in the production soon
