### ISSUE TITLE
org.jacuzzi.core.DatabaseException: Expected exactly one package for problemId = ?

### ISSUE THREAD

**Issue by MikeMirzayanov** [Codeforces/polygon-issue-tracking#222]
ERROR [2018-02-06 19:03:49,326] ApiPage: Unhandled exception during "contest.problems" api method request from User {id=5581, login='gassa', name='Ivan Kazmenko', email='gassa@mail.ru'} (ApiPage.java:108, http-bio-8081-exec-31)
org.jacuzzi.core.DatabaseException: Expected exactly one package for problemId = 59100
        at com.codeforces.polygon.dao.impl.PackageDaoImpl.findLatestByProblemId(PackageDaoImpl.java:41)
        at com.codeforces.polygon.web.misc.ApplicationModule.lambda$addDebugBinder$3(ApplicationModule.java:229)
        at com.codeforces.polygon.web.api.ProblemsListApiPage$ProblemForView.<init>(ProblemsListApiPage.java:71)

**Comment by FrolovAlex** [comment]
fixed
