### ISSUE TITLE
Программа на языке Python не может содержать букву "И" (русская, заглавная)

### ISSUE THREAD

**Issue by dkirienko** [Codeforces/polygon-issue-tracking#503]
В программах на языке Python нельзя использовать русскую заглавную букву "И". Это нужно, например, для вывода сообщений чекера.

Как воспроизвести. В разделе Source Files выбрать New file
Выбрать Language: Python.3, ввести имя.
В редакторе файла написать одну строку

`# И
`

Нажать на Save. Сохранение не получится, будет ошибка:
Traceback (most recent call last): File "<string>", line 1, in <module> File "C:\Programs\Python-3\lib\encodings\cp1251.py", line 23, in decode return codecs.charmap_decode(input,self.errors,decoding_table)[0] UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 3: character maps to <undefined> 

Все остальные буквы вроде можно использовать. Тест для проверки:

```
# АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ
# абвгдеёжзийклмнопрстуфхцчшщъыьэюя

```

Поиск в интернете наводит на мысль, что это какая-то легендарная проблема именно буквы "И".

**Comment by MikeMirzayanov** [comment]
Fixed
